import Head from "next/head";
import Posts from "~/components/posts";

const Home = () => {
 
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="grid grid-cols-1 sm:grid-cols-2  sm:divide-x divide-lime-600">
            <Posts />
        </div>
      </main>
    </>
  );
};

export default Home;
