import Head from "next/head";
import Image from "next/image";

import owenImage from "../../public/images/owen.png";

const Home = () => {
 
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="grid grid-cols-1 sm:grid-cols-2  sm:divide-x divide-white-600">
          <div className="flex flex-col text-white items-center">
            <h1 className="text-6xl tracking-wider mb-1 sm:mb-2">//B3T3 BLOG</h1>
            <div className="h-64 w-96 relative">
              <Image 
                src={owenImage}
                alt="Picture Of Myself"
                layout="fill"
                className="rounded-full h-60 w-90 relative"
              />
            </div>
          </div>
          <div className="text-white sm:pl-2 mt-4 sm:mt-0">
            <p className="text-6xl sm:text-8xl tracking-widest sm:m-6">Hi,</p>
            <p className="text-4xl sm:text-6xl tracking-widest sm:m-6">My name is Owen</p>
            <p className="text-2xl sm:text-3xl tracking-widest sm:m-6">And this is my T3 learning blog.</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
